version: '3.7'
services:

  #PHP Service
  app_php:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel
    container_name: app_php
    restart: unless-stopped
    tty: true
    ports: 
      - "8000:8000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver_nginx:
    image: nginx:alpine
    container_name: webserver_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db_mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: db_mssql
    restart: unless-stopped
    tty: true
    ports:
      - "1433:1433"
    volumes:
      - dbmssql:/var/opt/mssql
    networks:
      - app-network
    environment:
      #MYSQL_DATABASE: testing
      # MYSQL_ROOT_PASSWORD: allhailravelware1402
      MSSQL_SA_PASSWORD: allhailravelware1402
      SERVICE_TAGS: dev
      SERVICE_NAME: mssql
      ACCEPT_EULA: Y
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
    dbmssql:
      driver: local
